print('Print statement by feature/A branch')
print('some changes by hotfix')
print('second commit by feature/A branch')
print('new feature by feature/B')
print('hotfix 2 rebase example')
print('hotfix 2 rebase example ')
print('hotfix 2 rebase example ')
print('new feature by feature/B')
